### ISSUE TITLE
DTLS

### ISSUE THREAD

**Issue by pjbakker** [polarssl/polarssl#1]
Request for DTLS support as this would increase usability for my projects.

**Comment by hnrkp** [comment]
I'll just bump this. I'm investigating what library to use for an embedded commercial system that will use DTLS, and can't find any information with regards to DTLS support officially from PolarSSL. How's it coming..? :)

**Comment by jvermillard** [comment]
+1 :)

**Comment by mpg** [comment]
https://polarssl.org/tech-updates/releases/mbedtls-1.4-dtls-preview-released

Let us emphasize that this is a preview, not a new stable branch.

**Comment by jvermillard** [comment]
https://polarssl.org/download/polarssl-1.4-dtls-preview-gpl.tgz
404 ?

**Comment by mpg** [comment]
Oops, s/polarssl/mbedtls/ :) I just fixed the post. The download page already had the correct link: https://polarssl.org/download-archive
