### ISSUE TITLE
PolarSSL provides an unclear error if server key usage fails

### ISSUE THREAD

**Issue by andj** [polarssl/polarssl#142]
When running as a server, PolarSSL checks whether the client will accept its certificate (ssl_srv.c:875).

Unfortunately the error it provides is "POLARSSL_ERR_SSL_NO_CIPHER_CHOSEN", which translates to "no ciphersuites in common". ssl_srv.c:1565 

This is confusing to end users. The error should explain that no certificate matching the required EKU/KU could be found.

**Comment by mpg** [comment]
I just included the first part (issue a different error when there are ciphersuite in common but none of them was usable) in an internal branch for the next release, but I don't think we'll do the second part, for the reason mentionned in my previous message.

**Comment by andj** [comment]
Thanks, a better error message helps a lot. 

Life would be even better with more specific errors though. End-users don't have the time or the technical to go through the whole debugging process to find the cause. That's one of the problems many people have with OpenSSL: opaque error messages :). 

I'd hope you could make the error even clearer in the future. I can't think of a good solution other than some sort of "error stack" though.

**Comment by mpg** [comment]
How about debug messages?
