### ISSUE TITLE
iOS compiler warning fix incomplete in release-1.2 branch

### ISSUE THREAD

**Issue by sharkcz** [polarssl/polarssl#143]
The commit 0b0b522932ed70e93f18eca66dede570ea1a00a3 in release-1.2 branch is different from the development branch commit ef5087d150d5804e239878b17f357c9fee627883 in the chunk for the bn_mul.h file - it misses parenthesis around the "r >> biL" expression and it causes the code to enter an endless loop on the s390/s390x architectures. See https://bugzilla.redhat.com/show_bug.cgi?id=1167842 for a Fedora bug report.

**Comment by mpg** [comment]
Will be fixed in 1.2.13. Thanks for your report!
