### ISSUE TITLE
memory.h implements memory_set_own() and does not declare platform_set_malloc_free()

### ISSUE THREAD

**Issue by hkluis** [polarssl/polarssl#147]
Compiling an application against openssl 1.3.9 include files produces the following error on VisualStudio 6 (although the problem is not due to VS6):
    ..\polarssl\include\polarssl\memory.h(49) : error C2065: 'platform_set_malloc_free' : undeclared identifier

This is due to the following in memory.h:
    int memory_set_own( void * (*malloc_func)( size_t ), void (*free_func)( void * ) )
    {
        return platform_set_malloc_free( malloc_func, free_func );
    }

There are two problems.  First, this function should be conditionally compiled based on POLARSSL_PLATFORM_MEMORY, because platform_set_malloc_free() is declared in platform.h (and should only be implemented) based on that macro. 

Second, why is a function implemented in an include file?

**Comment by mpg** [comment]
Did you notice that `memory.h` is deprecated? I recommend using `platform.h` instead. That's the reason why the function is implemented in the header file, it allows use to keep just that file for compatibility reason, without an additional C file.

Anyway, this error is indeed a bug. I just fixed it for the next release. Thanks for reporting it.
