### ISSUE TITLE
gen_key is using a wrong default curve

### ISSUE THREAD

**Issue by LeoUnglaub** [polarssl/polarssl#149]
Hey,
if you use gen_key (or polarssl_gen_key on Crux Linux) with `type=ec` the default curve is secp521r1. However according to the documentation here https://polarssl.org/kb/cryptography/rsa-key-pair-generator the default is brainpoolP512r1.

Greetings
Leo

**Comment by mpg** [comment]
The default was changed sometime ago and the page wasn't updated. The output of `./gen_key help` however allways gives the up-to-date documentation.

I just updated the KB article, thanks for noticing and letting us know.
