### ISSUE TITLE
The aes functions should not trash the iv parameter

### ISSUE THREAD

**Issue by LemonBoy** [polarssl/polarssl#158]
I lost some time trying to track down a bug in my code where every decrypted block had a wrong hmac (which is the actual block IV) that happened because the IV array gets overwritten by temporary calculations.
You should at least mention this detail in the header, it could save quite some head scratching heh

**Comment by mpg** [comment]
The documentation of `aes_crypt_cbc` says: 

     * \param iv       initialization vector (updated after use)

Are you talking about another function or suggesting we make that more visible/explicit?

**Comment by LemonBoy** [comment]
I know, after some head banging I RTFM'd and figured out that my code was right, but at first I (wrongly) assumed it was working like OpenSSL does and spent too much time trying to find out what part of my code was behaving wrong.
I suggest not to update the parameter at all if that's not a problem

**Comment by mpg** [comment]
There is an excellent reason for updating the IV: it allows to encrypt a long message (eg a large file that you don't want to load in memory in full) by repeatedly calling `aes_crypt_cbc()`: the last block of chunk n will be used as "IV" for chunk n+1. I think I'll add a note about that in the doc.

Let me also mention the cipher module whose interface might be closest to what you were expecting.

**Comment by mpg** [comment]
I expanded the documentation to make it more explicit that the IV is updated and why.
