### ISSUE TITLE
Tests fail with shared library

### ISSUE THREAD

**Issue by aw** [polarssl/polarssl#167]
When compiled with `SHARED=on`, all tests search for `libmbedtls.so.7` but the _soname_ should actually be `libmbedtls.so.8`.

I believe it's from here: https://github.com/polarssl/polarssl/blob/development/library/Makefile#L25

**Comment by mpg** [comment]
You're right. We just found that independently yesterday. The short-term fix is to change line 25 in the Makefile as you say and we'll try to publish a fixed version soon.

**Comment by aw** [comment]
:+1: awesome, thanks!

**Comment by mpg** [comment]
The tarball on the website has been updated today, see the end of https://polarssl.org/tech-updates/releases/mbedtls-1.3.10-released

Thanks again for reporting the issue.
