### ISSUE TITLE
SHA256 Failure

### ISSUE THREAD

**Issue by DomT4** [polarssl/polarssl#173]
Hey folks,

The SHA256 checksum of https://polarssl.org/download/mbedtls-1.3.10-gpl.tgz suddenly changed in the last 12 hours or so. As per the release [blog](https://polarssl.org/tech-updates/releases/mbedtls-1.3.10-released) several days ago the SHA256 should be:

![screen shot 2015-02-16 at 17 41 19](https://cloud.githubusercontent.com/assets/6998367/6216609/aeac10a4-b603-11e4-8cf9-18d71765f128.png)

But I'm currently getting:

![screen shot 2015-02-16 at 17 41 41](https://cloud.githubusercontent.com/assets/6998367/6216618/bb957f80-b603-11e4-934c-37839daafaf5.png)

Can someone verify if this was a repack or something more concerning? The Github log here would indicate a repack, but some clarity would be good. There's no security contact on the website, hence the rather public post here. Some clarity on the situation would be great, Thanks!

**Comment by mpg** [comment]
1.3.10 was repackaged today to fix a wrong soversion in the makefile. I've just updated the blog post to mention that and provide the new hashes (after carefully checking the tarball of course). Thanks for the reminder and sorry for the inconvenience.

**Comment by DomT4** [comment]
Thanks for the swift reply, Appreciated! Thought it best to check it wasn't something more concerning given the nature of the software.

**Comment by mpg** [comment]
I agree, you were right to be careful. Hashes are of no use if no-one cares when they're wrong ^^
